#!/usr/bin/python

# Copyright (c) 2014 Yandex LLC. All rights reserved.

# This file is part of Handystats.

# Handystats is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# Handystats is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import sys
import json

from handystats.statistics import Data

def append_dump(metrics, dump):
    if isinstance(dump, str):
        dump = json.loads(dump)
    elif not isinstance(dump, dict):
        raise TypeError

    for name, value in dump.iteritems():
        data = Data.from_json(json.dumps(value, separators=(',',':')))

        if name not in metrics:
            metrics[name] = data
        else:
            metrics[name].append(data)

def aggregate_log(log_file):
    metrics = dict()
    unixtime = 0

    for line in log_file:
        if not line:
            continue

        unixtime, dump = line.split(' ', 1)
        append_dump(metrics, dump)

    return unixtime, metrics

def main():
    unixtime, metrics = aggregate_log(sys.stdin)

    def data_to_dict(data):
        return json.loads(data.to_json())

    print unixtime, json.dumps(metrics, default=data_to_dict, separators=(',',':'))

if __name__ == "__main__":
    main()
